In [3]:
import numpy as np

In [4]:
m_list=[1,2,3]

In [5]:
arr = np.array(m_list)

In [6]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((2,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

#### it divides the distance between(0-5) to 10 equal parts.

In [12]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

##### identity matrix:
two dimensional square matrix and you have a diagonal of ones and everything else is zeroes

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### random with uniform distribution

In [14]:
np.random.rand(4,5)

array([[0.64110628, 0.74317742, 0.73053657, 0.71734985, 0.19615565],
       [0.47197828, 0.80798256, 0.01135471, 0.28671197, 0.05040902],
       [0.64790626, 0.62901749, 0.71990761, 0.80700103, 0.71903496],
       [0.5749482 , 0.67416318, 0.19034721, 0.82351533, 0.53452234]])

#### standard normal distribution or gaussian

In [15]:
np.random.randn(5)

array([-0.67537271,  0.18794153,  0.2812836 ,  0.57001589, -0.36232836])

#### random integers from low to high numbers

In [16]:
np.random.randint(2,100,5)

array([14, 70, 76, 43, 71])

In [17]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
ranarr=np.random.randint(0,50,10)
ranarr

array([10, 27, 20, 17, 32, 24,  9, 18, 26,  6])

##### Reshape

In [19]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### max min index

In [20]:
ranarr.max()

32

In [21]:
ranarr.min()

6

In [22]:
ranarr.argmax() # will return the index of maximim value

4

In [28]:
ranarr.argmin()

9

#### shape reshape dtype

In [29]:
arr.shape

(25,)

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
arr.dtype

dtype('int32')

### numpy indexing and selection

In [32]:
import numpy as np

In [33]:
arr = np.arange(0,11)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr[1:5]

array([1, 2, 3, 4])

 #### Numpy broadcasting

In [36]:
arr[5:8]=100

In [37]:
arr

array([  0,   1,   2,   3,   4, 100, 100, 100,   8,   9,  10])

In [38]:
# this is just a view of main arr so by chaning this tha main arr will change too 
arr_view=arr[1:5]

In [39]:
arr_view

array([1, 2, 3, 4])

In [40]:
arr_view[:]=100

In [41]:
arr_view

array([100, 100, 100, 100])

In [42]:
arr

array([  0, 100, 100, 100, 100, 100, 100, 100,   8,   9,  10])

In [43]:
# to prevent this issue he have to make a copy of arr

In [44]:
arr = np.arange(0,11)
arr_copy= arr.copy()

In [45]:
arr_copy[:]=100

In [46]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### two dimenssion array

In [2]:
import numpy as np
arr_2d= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr_2d[0][0]

1

In [5]:
arr_2d[0]

array([1, 2, 3])

In [7]:
arr_2d[1,2]

6

#### grab certain parts of entire matrix

In [11]:
arr_2d[:2,:1]

array([[1],
       [4]])

#### conditional selection

In [17]:
arr= np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
boolean_Arr= arr>5
boolean_Arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [23]:
arr[boolean_Arr]

array([ 6,  7,  8,  9, 10])