In [3]:
import numpy as np

In [4]:
m_list=[1,2,3]

In [5]:
arr = np.array(m_list)

In [6]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((2,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

#### it divides the distance between(0-5) to 10 equal parts.

In [12]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

##### identity matrix:
two dimensional square matrix and you have a diagonal of ones and everything else is zeroes

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### random with uniform distribution

In [14]:
np.random.rand(4,5)

array([[0.64110628, 0.74317742, 0.73053657, 0.71734985, 0.19615565],
       [0.47197828, 0.80798256, 0.01135471, 0.28671197, 0.05040902],
       [0.64790626, 0.62901749, 0.71990761, 0.80700103, 0.71903496],
       [0.5749482 , 0.67416318, 0.19034721, 0.82351533, 0.53452234]])

#### standard normal distribution or gaussian

In [15]:
np.random.randn(5)

array([-0.67537271,  0.18794153,  0.2812836 ,  0.57001589, -0.36232836])

#### random integers from low to high numbers

In [16]:
np.random.randint(2,100,5)

array([14, 70, 76, 43, 71])

In [17]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
ranarr=np.random.randint(0,50,10)
ranarr

array([10, 27, 20, 17, 32, 24,  9, 18, 26,  6])

##### Reshape

In [19]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### max min index

In [20]:
ranarr.max()

32

In [21]:
ranarr.min()

6

In [22]:
ranarr.argmax() # will return the index of maximim value

4

In [28]:
ranarr.argmin()

9

#### shape reshape dtype

In [29]:
arr.shape

(25,)

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
arr.dtype

dtype('int32')